### ISSUE TITLE
 video is not functioning,will someone please help me out in this? 

### ISSUE THREAD

**Issue by Divya871** [amirsanni/Video-Call-App-NodeJS#49]

**Comment by Divya871** [comment]
C:\Users\Harish\Desktop\Project-MS\src\ws\stream.js:8
        if ( socket.adapter.rooms[data.room].length> 1 ) {
                                             ^

TypeError: Cannot read property 'length' of undefined
    at Socket.<anonymous> (C:\Users\Harish\Desktop\Project-MS\src\ws\stream.js:8:46)
    at Socket.emit (events.js:376:20)
    at Socket.emitUntyped (C:\Users\Harish\Desktop\Project-MS\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Harish\Desktop\Project-MS\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[nodemon] app crashed - waiting for file changes before starting...
